import type { Product } from "./cart-context";

export const CATEGORIES = [
  { id: "todos", label: "Todos" },
  { id: "chocolate", label: "Chocolate" },
  { id: "frutas", label: "Frutas" },
  { id: "classicos", label: "Clássicos" },
  { id: "especiais", label: "Especiais" },
];

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: "Bolo de Chocolate Suíço",
    price: 89.9,
    priceFormatted: "R$ 89,90",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?q=80&w=800&auto=format&fit=crop",
    category: "chocolate",
    badge: "Mais Vendido",
    description: "Camadas de massa fofinha de cacau belga com ganache de chocolate suíço derretendo na boca. A escolha certa para os amantes de chocolate.",
  },
  {
    id: 2,
    name: "Red Velvet Sublime",
    price: 110.0,
    priceFormatted: "R$ 110,00",
    image: "https://images.unsplash.com/photo-1616541823729-00fe0aacd32c?q=80&w=800&auto=format&fit=crop",
    category: "classicos",
    badge: "Novo",
    description: "O clássico americano em versão artesanal: massa aveludada vermelha com cream cheese cremoso e notas sutis de baunilha e cacau.",
  },
  {
    id: 3,
    name: "Cenoura com Brigadeiro",
    price: 65.0,
    priceFormatted: "R$ 65,00",
    image: "https://images.unsplash.com/photo-1588195538326-c5b1e9f80a1b?q=80&w=800&auto=format&fit=crop",
    category: "classicos",
    description: "O favorito brasileiro em versão premium: massa úmida de cenoura coberta com brigadeiro artesanal de qualidade superior.",
  },
  {
    id: 4,
    name: "Limão Siciliano Decorado",
    price: 95.0,
    priceFormatted: "R$ 95,00",
    image: "https://images.unsplash.com/photo-1535141192574-5d4897c12636?q=80&w=800&auto=format&fit=crop",
    category: "frutas",
    description: "Aroma cítrico e refrescante com creme de limão siciliano importado e merengue tostado na hora. Uma obra de arte gastronômica.",
  },
  {
    id: 5,
    name: "Morango com Chantilly",
    price: 85.0,
    priceFormatted: "R$ 85,00",
    image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?q=80&w=800&auto=format&fit=crop",
    category: "frutas",
    badge: "Favorito",
    description: "Morangos frescos selecionados sobre camadas de chantilly artesanal e pão de ló úmido. Elegância e leveza em cada garfada.",
  },
  {
    id: 6,
    name: "Trufa de Nozes",
    price: 120.0,
    priceFormatted: "R$ 120,00",
    image: "https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?q=80&w=800&auto=format&fit=crop",
    category: "especiais",
    description: "Massa aerada com nozes caramelizadas e ganache de chocolate amargo 70%. Um bolo sofisticado para ocasiões especiais.",
  },
  {
    id: 7,
    name: "Floresta Negra",
    price: 105.0,
    priceFormatted: "R$ 105,00",
    image: "https://images.unsplash.com/photo-1571115177098-24ec42ed204d?q=80&w=800&auto=format&fit=crop",
    category: "chocolate",
    description: "O clássico alemão com cereja ácida, kirsch artesanal e chocolate amargo. Layers perfeitas que revelam profundidade a cada fatia.",
  },
  {
    id: 8,
    name: "Baunilha Bourbon",
    price: 78.0,
    priceFormatted: "R$ 78,00",
    image: "https://images.unsplash.com/photo-1542826438-bd32f43d626f?q=80&w=800&auto=format&fit=crop",
    category: "classicos",
    description: "Simplicidade elevada ao máximo: massa branca com fava de baunilha bourbon, cobertura de cream cheese e morangos silvestres.",
  },
];
